### ISSUE TITLE
Not created: eyewitness_io_statuses

### ISSUE THREAD

**Issue by axtg** [eyewitness/eye#10]
Hi,

I just installed your package via Composer, but ran into trouble.
First off I needed to set Schema::defaultStringLength(); due to database limitations locally (on MySQL). I then cleaned the failed install and ran the install command again.

[X] All migrations succeeded (so the installer said)
[X] API keys were created
[ ] The test showed that [db].eyewitness_io_statuses and history_monitors were not available. This table wasn't mentioned in the migration list. On launch the same error is thrown.

The vendor eye folder does have the migration, so I am unsure why this migration is not run.
I copied over the migration files to the app's main migration folder and ran migrate to solve this now. Could be a one off thing, but FYI.

**Comment by laurencei** [comment]
Thanks @axtg,

I've pushed a change so no default schema length is over 191 now. This should remove the need to add `Schema::defaultStringLength()`. Do you mind checking if this is correct? I'm keen for people to be able to install the package in any situation without any code changes.

In regards to the missing table - I'm going to assume that was related to the database error. I cant see any other reason why. But I will keep an eye on it.

**Comment by axtg** [comment]
Indeed, as expected, the defaultStringLength() glitch broke the installer and thus it's migrations. I did a clean install with the latest changed and confirmed it working all the way through. Closing.
