### ISSUE TITLE
Assets not found!

### ISSUE THREAD

**Issue by xembill** [eyewitness/eye#12]
eyewitness.css and eyewitness.js assets file not found.

**Comment by laurencei** [comment]
Hi @xembill ,

Do you mind providing some more information about the exact error you are getting? The compliled `.css.` and `.js. files are included in the package, and we have special routes to them, so it should work out of the box.

**Comment by xembill** [comment]
`https://*********.info/eyewitness/asset/1518612813/eyewitness.css` 
its just not found. maybe my nginx or htaccess file broken I dont know why.

**Comment by laurencei** [comment]
I think your server config is not sending all 404's or `.css/.js` through to Laravel. The css and js are actually provided by a route.

I might add an option to publish the files for this situation

**Comment by xembill** [comment]
I change my nginx settings and works! 
delete =>  `location ~* \.(jpg|jpeg|gif|css|png|js|ico|html)$ {
		expires max;
}`

But maybe assets file will publishable

**Comment by gauravcanon** [comment]
Hi @xembill I am having still same issue 
<img width="1437" alt="screenshot 2019-03-04 14 01 47" src="https://user-images.githubusercontent.com/897747/53720172-14fa5280-3e86-11e9-9a26-6ed9ee849db8.png">
