### ISSUE TITLE
Conditional shceduled tasks show incorrect Error status

### ISSUE THREAD

**Issue by 36864** [eyewitness/eye#13]
I have a conditional task in my scheduler defined as such:
```
$schedule->job(new SendNotificationEmails)
			->everyMinute()
			->when(function() {
			 return Notification::
				 where('notified', 0)
				 ->where('notifying', 0)
				 ->where('notify_at', '<', now())
				 ->exists();
});
```

Now, this doesn't actually run very often, but I need it to check if it needs to run every minute. The result is that eyewitness sees a job that should run every minute, but doesn't run for long periods of time and displays the job's status as Error in the dashboard view, even though everything is working as intended and no jobs have failed: 
![](https://my.mixtape.moe/ykpazx.png)

I'm not sure if this is something that you can even check at all, but maybe have a setting to mark a job as conditional and give it a special status indicator would be a decent approach to this.

**Comment by laurencei** [comment]
Hmm... it's tricky. Part of the problem is what happens if this job actually never runs, if we disable the alert for it, you will never ever know the job has stopped working.

Personally - I'm not entirely sure the "logic" of notifications should be in your scheduler. i.e. what is wrong with just `$schedule->job(new SendNotificationEmails)->everyMinute()`? Then let the job itself decide what to do?

Because I am assuming that the `Notification::where(..)` logic is duplicated in your job as well (in order to filter the ones to send)?

I'll have a think further about it...

**Comment by 36864** [comment]
The point of conditional task scheduling is to not clog up the queue with jobs that aren't gonna run anyway.

I understand that there probably isn't a good way to monitor these cases, which is why I suggested allowing a user to set a job as "conditional" as a way to say "Don't worry about this job if it doesn't run for a long time, but do still notify me if it it fails when it does run".

**Comment by laurencei** [comment]
Ok - gotcha.

In that case you can go to the settings option of that scheduler and set `Send alert if cron schedule is missed` to false.

You will still get an alert if the job exits with an error - but no alert will be sent if/when the job doesnt run at all.

Can you try and and confirm it does what you need?

**Comment by 36864** [comment]
I do have that option disabled, and I don't get any notifications, but on the dashboard, the displayed status is still ERROR.

I did try setting it to On for a few minutes, and I still didn't get any notifications - possibly a separate issue entirely, or maybe a behavior that suggests something is being called (meaning the schedule isn't missed) but since no jobs are dispatched, Eyewitness still thinks it failed?

**Comment by laurencei** [comment]
> I did try setting it to On for a few minutes, and I still didn't get any notifications - possibly a separate issue entirely,

What happens is Eyewitness will wait for it to become "active", then if/when it misses and becomes "fail" again - it will alert you. i.e. it already knows it was failed, so it wont re-alert you.

But I understand now about the "failed" message. I'll look into another way to display it.

**Comment by laurencei** [comment]
Hi @36864 - we've pushed a new feature today that includes a "last run time" alert. This means you can set a large window (say 24 hours) for when the job must run at least once.

You can read more about it here: https://docs.eyewitness.io/monitors/scheduler#conditional-schedules

Please let me know if you have any further issues.
