### ISSUE TITLE
ERROR: syntax error at or near "day"

### ISSUE THREAD

**Issue by mavrck** [eyewitness/eye#15]
Hey all,

I'm not sure if I'm doing anything wrong, but I'm having issues getting things setup. After entering the creditials and hitting the dashboard route throws errors for me. The eyewitness_io_history_monitors table does exist and has a few rows in it.

Let me know what other information I can provide to help track this down.

Thanks!

-----------

Error:
`SQLSTATE[42601]: Syntax error: 7 ERROR: syntax error at or near "day"`

SQL:
`select avg(value) as avg_size, DATE(created_at) day from "eyewitness_io_history_monitors" where "meta" = pgsql and "type" = database group by "day"`

Environment:
- Laravel 5.4
- Homestead 7.0.1
- PHP 7.2.0RC2
- Postgres 9.3.5

**Comment by mavrck** [comment]
<img width="1050" alt="screen shot 2018-02-17 at 9 20 30 pm" src="https://user-images.githubusercontent.com/2243265/36347647-6652d83c-142a-11e8-9541-65fc26cb2c53.png">

**Comment by laurencei** [comment]
Thanks - I'm looking into it now and will get back to your shortly.

**Comment by laurencei** [comment]
Ok - I think this is how Postgres handles SQL aggregate stuff slightly different to mySQL. It is actually a similar issue to https://github.com/eyewitness/eye/issues/6

I've got an idea how to solve both - so I'll get it done and push an update today for everyone.

**Comment by laurencei** [comment]
@mavrck - I've just pushed an update that now uses Laravel collections to do all the logic, so there is no longer a reliance on the database.

Do you mind grabbing the latest version of the beta and trying again? I think this should solve the issue for you.

**Comment by PKeidel** [comment]
Problem is fixed with the latest commit, thanks for your fast reaction.

**Comment by mavrck** [comment]
Thanks @laurencei! Looks good to me now.
