### ISSUE TITLE
undefined index: 'information' in Ssl.php:162

### ISSUE THREAD

**Issue by PKeidel** [eyewitness/eye#16]
Hi, I've activated the SSL check and it gives me this error in my logfile:

undefined index: 'information' in app/Monitors/Ssl.php:162

https://github.com/eyewitness/eye/blob/beta/app/Monitors/Ssl.php#L162

When i'm home I can `dd($result)` to see whats inside to give you some more information.

**Comment by laurencei** [comment]
Thanks @PKeidel,

Yeah - if you can capture the output of `dd($result)` and send to me, that would be a big help. To reach that point, it means the SSL certificate got a valid response from the API. The API says that all those fields are always provided, so I'll be interested to see whats going on.

As this will contain potentially sensitive information about your certificate - it might easier to email the output to `support {at} eyewitness {dot} io` - and I can look at it there...

**Comment by laurencei** [comment]
Actually - you would probably need to do `\Log::info(print_r($result, true)));` inside the function to capture it, since it'll run in the background.

**Comment by PKeidel** [comment]
I just send you an email with the output, the `certificates` array is completely empty.

**Comment by laurencei** [comment]
This issue has been identified and fixed in the latest version today. Essentially what occured was the website firewall was blocking the certificate check, causing some variables to not be available.
