### ISSUE TITLE
ERR value is not an integer or out of range

### ISSUE THREAD

**Issue by indigoram89** [eyewitness/eye#17]
`Predis\Response\ServerException ERR value is not an integer or out of range 
    vendor/predis/predis/src/Client.php:370 Predis\Client::onErrorResponse
    vendor/predis/predis/src/Client.php:335 Predis\Client::executeCommand
    vendor/predis/predis/src/Client.php:314 Predis\Client::__call
    vendor/laravel/framework/src/Illuminate/Redis/Connections/Connection.php:96 Illuminate\Redis\Connections\Connection::command
    vendor/laravel/framework/src/Illuminate/Redis/Connections/Connection.php:108 Illuminate\Redis\Connections\Connection::__call
    vendor/laravel/framework/src/Illuminate/Cache/RedisStore.php:141 Illuminate\Cache\RedisStore::increment
    vendor/laravel/framework/src/Illuminate/Cache/Repository.php:279 Illuminate\Cache\Repository::increment
    vendor/laravel/framework/src/Illuminate/Cache/CacheManager.php:304 Illuminate\Cache\CacheManager::__call
    vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:221 Illuminate\Support\Facades\Facade::__callStatic
    vendor/eyewitness/eye/app/Queue/Jobs/SonarBase.php:68 Eyewitness\Eye\Queue\Jobs\SonarBase::handle
    [internal] call_user_func_array
    vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:29 Illuminate\Container\BoundMethod::Illuminate\Container\{closure}
    vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:87 Illuminate\Container\BoundMethod::callBoundMethod
    vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:31 Illuminate\Container\BoundMethod::call
    vendor/laravel/framework/src/Illuminate/Container/Container.php:549 Illuminate\Container\Container::call
    vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php:94 Illuminate\Bus\Dispatcher::Illuminate\Bus\{closure}
    vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:114 Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
    vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:102 Illuminate\Pipeline\Pipeline::then
    vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php:98 Illuminate\Bus\Dispatcher::dispatchNow
    vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php:49 Illuminate\Queue\CallQueuedHandler::call
    vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php:76 Illuminate\Queue\Jobs\Job::fire
    vendor/laravel/framework/src/Illuminate/Queue/Worker.php:320 Illuminate\Queue\Worker::process
    vendor/eyewitness/eye/app/Queue/Worker.php:29 Eyewitness\Eye\Queue\Worker::process
    vendor/laravel/framework/src/Illuminate/Queue/Worker.php:270 Illuminate\Queue\Worker::runJob
    vendor/laravel/framework/src/Illuminate/Queue/Worker.php:114 Illuminate\Queue\Worker::daemon
    vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php:101 Illuminate\Queue\Console\WorkCommand::runWorker
    vendor/eyewitness/eye/app/Commands/Framework/WorkCommand.php:27 Eyewitness\Eye\Commands\Framework\WorkCommand::runWorker
    vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php:85 Illuminate\Queue\Console\WorkCommand::handle
    [internal] call_user_func_array
    vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:29 Illuminate\Container\BoundMethod::Illuminate\Container\{closure}
    vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:87 Illuminate\Container\BoundMethod::callBoundMethod
    vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:31 Illuminate\Container\BoundMethod::call
    vendor/laravel/framework/src/Illuminate/Container/Container.php:549 Illuminate\Container\Container::call
    vendor/laravel/framework/src/Illuminate/Console/Command.php:183 Illuminate\Console\Command::execute
    vendor/symfony/console/Command/Command.php:252 Symfony\Component\Console\Command\Command::run
    vendor/laravel/framework/src/Illuminate/Console/Command.php:170 Illuminate\Console\Command::run
    vendor/symfony/console/Application.php:946 Symfony\Component\Console\Application::doRunCommand
    vendor/symfony/console/Application.php:248 Symfony\Component\Console\Application::doRun
    vendor/symfony/console/Application.php:148 Symfony\Component\Console\Application::run
    vendor/laravel/framework/src/Illuminate/Console/Application.php:88 Illuminate\Console\Application::run
    vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php:121 Illuminate\Foundation\Console\Kernel::handle
    artisan:37 [main]`

**Comment by laurencei** [comment]
Thansks @indigoram89 ,

I've looked into it. I've got some theories why - but can you clarify the following for me to help pinpoint the issue;

1. Was this on a new install of Eyewitness - or have you been using it for a few days/weeks without issue?
2. Your PHP and Laravel versions.
3. Was this a one-off error - or does it keep occuring?

I'll then get a fix implemented ASAP.

**Comment by indigoram89** [comment]
1. I use Eyewitness for a few days and without problem. After we move our project to another server provider and this error began to appear every day:
2. PHP 7.2 and Laravel 5.5.36 (using laravel forge and envoyer).
3. Information on screenshot:

<img width="667" alt="2018-03-05 12 13 53" src="https://user-images.githubusercontent.com/10687211/36960938-2b51cc92-206f-11e8-8f29-11bd50cdd722.png">

**Comment by indigoram89** [comment]
@laurencei, yes, I try tomorrow.

**Comment by indigoram89** [comment]
@laurencei the error is not repeated yet :)
