### ISSUE TITLE
SSL API invalid result

### ISSUE THREAD

**Issue by indigoram89** [eyewitness/eye#19]
<img width="995" alt="2018-03-11 10 09 34" src="https://user-images.githubusercontent.com/10687211/37250757-5916d16e-2514-11e8-9e6b-cbdda01afafb.png">

**Comment by laurencei** [comment]
Thanks @indigoram89 - are there any further details in the "breadcrumbs" etc? Part of the log should contain the array of the `$result` that was invalid:

`$this->eye->logger()->error('SSL API invalid result', print_r($result, true), $domain);`

If you want to email it to me if it contains personal data - I can work out why it failed: laurence@eyewitness.io

Of if you are happy to post it here - I'll check it out.

**Comment by indigoram89** [comment]
@laurencei I don't have any logs for this error. But I have exception for error "Eyewitness: Unable to start SSL scan":

![img-2018-03-11-11-34-31](https://user-images.githubusercontent.com/10687211/37251393-55ee898a-2520-11e8-9198-f7fda0d07814.png)

**Comment by indigoram89** [comment]
@laurencei maybe this information can be useful:

![img-2018-03-11-11-36-30](https://user-images.githubusercontent.com/10687211/37251402-8e3a7312-2520-11e8-83ae-45202b720a70.png)

**Comment by laurencei** [comment]
Thanks.

Just to confirm - the scan has been working before this ok? And has it been working ok afterwards?

Looking at the logs, and looking at the code - I have a feeling this was a temporarily unavailablilty of the SSL API scanning endpoint...

**Comment by indigoram89** [comment]
@laurencei it was a week ago. I disable SSl scan for me.

**Comment by laurencei** [comment]
@indigoram89 - if you get a chance - can you try and reanble and see what happens?

It looks like a temporary error here, or perhaps a firewall blocking?

**Comment by indigoram89** [comment]
@laurencei ok

**Comment by laurencei** [comment]
Hi @indigoram89 - just touching base - did the SSL Checks start working for you again?

**Comment by laurencei** [comment]
At this stage it looks like this was a temporary outage of the API for SSL scans. There's been no other reports of the issue, and we've also improve SSL scanning a little since this time.

Please let me know if you run into any further issues relating to this.

**Comment by kfirba** [comment]
@laurencei Hey.

I get the same error but due to another issue. I'm monitoring 13 application domains and running the SSL check against all of them each hour means 312 scans per day. The API for SSL scans stops you at 251 scans per day:

> You have performed 251 tests in the last 24 hours. The system is currently busy, please try again a bit later.

I guess we need some way to tell Eyewitness how often it should re-check the certs. I think that running the command every hour is a little bit of an over-kill. Maybe we should run it every 3 hours?

What do you think?

**Comment by laurencei** [comment]
@kfirba - makes sense.

Perhaps we should make it a config option?

**Comment by kfirba** [comment]
Sounds good. Maybe it’s an opportunity to expose config option for each
monitor scheduled job (including custom monitors)

**Comment by kfirba** [comment]
@laurencei anything new regards this issue?
