### ISSUE TITLE
Undefined property: Eyewitness\Eye\Queue\Jobs\Sonar::$end_time

### ISSUE THREAD

**Issue by indigoram89** [eyewitness/eye#20]
<img width="975" alt="2018-03-11 10 10 22" src="https://user-images.githubusercontent.com/10687211/37250758-78e521e4-2514-11e8-9024-750267042a7e.png">

**Comment by laurencei** [comment]
Thanks @indigoram89 -  I've just pushed a patch right now that will fix this exact issue.

**Comment by indigoram89** [comment]
@laurencei, thank you!
