### ISSUE TITLE
History of schedules doesn't work

### ISSUE THREAD

**Issue by ErnestStaug** [eyewitness/eye#22]
Hello,

I've noticed that `scheduler` history part doesn't work.

If the process running more often than every 6h for 2 months it just gives me `500 error` when ever I try to access the information about scheduled task (e.g. `eyewitness/schedulers/1`).

It  seems that it's trying to load all the records at once and it takes too long and just times out.
( Possible fix? Split records to `50 limit`  and load __on demand__ rest of it? )

**Comment by laurencei** [comment]
The latest patch today includes automatic pagination if there are too many results. Please let me know if you have any further issues.
