### ISSUE TITLE
Call to undefined function Eyewitness\Eye\Notifications\resolve()

### ISSUE THREAD

**Issue by CaptainHypertext** [eyewitness/eye#25]
When I add myself as a recipient and try to send a test via email, I get this error:
`Call to undefined function Eyewitness\Eye\Notifications\resolve() in /vendor/eyewitness/eye/app/Notifications/Notifier.php at line 46`

I'm on Laravel 5.2, my version is dev-beta

**Comment by laurencei** [comment]
Hi @CaptainHypertext - I've just pushed a commit that will fix this.

If you grab the latest version of the package - it should work correctly.

**Comment by CaptainHypertext** [comment]
@laurencei Also much appreciated!
