### ISSUE TITLE
Unable to map the Failed Job

### ISSUE THREAD

**Issue by indigoram89** [eyewitness/eye#26]
<img width="1015" alt="2018-03-19 12 37 14" src="https://user-images.githubusercontent.com/10687211/37588109-4d52c18a-2b72-11e8-8d32-29c61b155da7.png">

**Comment by laurencei** [comment]
@indigoram89 - did you do a package upgrade today? The reason I ask is we just made some changes to this exact part of code for another issue.

I'm trying to work out if this is from the "new" package today, or the older version (which means it might already be fixed).

**Comment by indigoram89** [comment]
@laurencei 

Eyewitness version 3.0.0

**Comment by laurencei** [comment]
I think this has been fixed by a couple of updates since this was reported. If it continues - please let me know
