### ISSUE TITLE
Unable to send Database notification

### ISSUE THREAD

**Issue by forgueam** [eyewitness/eye#27]
I've got roughly 20 or so jobs. All seem to run fine, however, Eyewitness continually throws errors for one specific job. Every hour the same three things happen:

1. I get a warning that "The scheduled cron command *eyewitness:poll* has exited with an error"
1. A Laravel "Unable to send Database notification" exception is thrown
1. A few minutes later a notification that "The scheduled cron command *netsuite:import-amazon-orders* is now working"

As far as I can tell, my **netsuite:import-amazon-orders** command is running fine with no errors, so I'm not quite sure what is going on.

![screenshot from 2018-03-29 09-59-15](https://user-images.githubusercontent.com/224097/38093064-e06e4418-3337-11e8-991c-0bd998080a47.png)

PHP version
7.1.6

Laravel version
5.5.39

Eyewitness version
3.0.0

**Comment by laurencei** [comment]
Thanks @forgueam - I've pushed a patch. Can you update to the latest version of Eyewitness?

There's possibly two seperate issues - but I've fixed the one I am sure about. This might provide better clarity on the second issue, or resolve it as well.

Can you let me know how it goes once it's updated? Thanks!

**Comment by forgueam** [comment]
@laurencei that did the trick, thanks!
