### ISSUE TITLE
Undefined variable: domain

### ISSUE THREAD

**Issue by CaptainHypertext** [eyewitness/eye#28]
Had this message pop up for me last night, thought I'd pass it along.

**Undefined variable: domain**

File
/var/www/myapp/vendor/eyewitness/eye/app/Api.php at line 151

Stack Trace
0 /var/www/myapp/vendor/eyewitness/eye/app/Api.php(151): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(8, 'Undefined varia...', '/var/www/myapp...', 151, Array)
1 /var/www/myapp/vendor/eyewitness/eye/app/Monitors/Ssl.php(93): Eyewitness\Eye\Api->sslResult('146782ba10f2cc7...')=
2 /var/www/myapp/vendor/eyewitness/eye/app/Monitors/Ssl.php(47): Eyewitness\Eye\Monitors\Ssl->getResults('https://staging...')
3 /var/www/myapp/vendor/eyewitness/eye/app/Commands/Monitors/SslCommand.php(59): Eyewitness\Eye\Monitors\Ssl->result()
4 [internal function]: Eyewitness\Eye\Commands\Monitors\SslCommand->handle()
5 /var/www/myapp/vendor/laravel/framework/src/Illuminate/Container/Container.php(507): call_user_func_array(Array, Array)
6 /var/www/myapp/vendor/laravel/framework/src/Illuminate/Console/Command.php(169): Illuminate\Container\Container->call(Array)
7 /var/www/myapp/vendor/symfony/console/Command/Command.php(256): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
8 /var/www/myapp/vendor/laravel/framework/src/Illuminate/Console/Command.php(155): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
9 /var/www/myapp/vendor/symfony/console/Application.php(794): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
10 /var/www/myapp/vendor/symfony/console/Application.php(186): Symfony\Component\Console\Application->doRunCommand(Object(Eyewitness\Eye\Commands\Monitors\SslCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
11 /var/www/myapp/vendor/symfony/console/Application.php(117): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
12 /var/www/myapp/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(107): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
13 /var/www/myapp/artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
14 {main}

**Comment by laurencei** [comment]
Thanks @CaptainHypertext - I've pushed a fix for that in the latest beta version now.
