### ISSUE TITLE
Documentation URL

### ISSUE THREAD

**Issue by denismarinov** [eyewitness/eye#30]
I was excited when I found out about this and proposed it to use in the company I work. However, when I tried to open the documentation all the excitement was gone. Endless loading of ...

https://docs.eyewitness.io/getting-started/installation

**Comment by laurencei** [comment]
@denismarinov - sorry you ran into issues.

I just checked - and the docs are loading for me: 

![image](https://user-images.githubusercontent.com/1210658/39057711-42cae0c2-44fd-11e8-95ac-4b9dd8fac527.png)

Can you please try again? If it doesnt work, are you able to try a different browser? Also, please let me know what browser/version etc you are using - and I'll try to replicate it on my end here.

**Comment by denismarinov** [comment]
@laurencei The issue persists. I am using Chrome Version 65.0.3325.181 (Official Build) (64-bit). I've tried on Firefox 59.0.2 (64-bit) and Opera 52.0.2871.64. Still nothing. I also tried through a VPN and it works. Might be some ISP related issue. Will try later from a different ISP.

Thanks again for the quick response.

**Comment by laurencei** [comment]
Ok cool - sounds like a traffic issue of some sort then.

Please let me know how it goes. If you run into any other issues - also try opening the Dev Tools (F12) and see if there are any console errors?

We actually host our docs on https://www.gitbook.com/ - so if there are further issues I'm happy to try and get this resolved for you.

**Comment by denismarinov** [comment]
Maybe indeed was some traffic issue. It works good now.
