### ISSUE TITLE
Disabled SSL grade change alerts, but they still come

### ISSUE THREAD

**Issue by CaptainHypertext** [eyewitness/eye#34]
We keep getting alerts from Eyewitness that our SSL grade score has changed.  This happens maybe a couple times a day, so I changed the severity of these alerts to "Disabled", but that hasn't stopped them.  Is this a bug?

Any help is appreciated.

**Comment by laurencei** [comment]
Hi @CaptainHypertext ,

Just thinking outloud - you might need to run `config:cache` and `queue:restart` to make sure the new config has replicated across?

In regards to the original issue of the score changing constantly - the API uses the HT Bridge scan `https://www.htbridge.com/ssl/`

You can look at the report/score and see why it is constantly changing. It might be an indication of a configuration issue.

Let me know how it goes and we can look into it further for you.

**Comment by CaptainHypertext** [comment]
Thanks @laurencei ,
Well, we do use configuration cache and a queue... does Laravel's config power Eyewitness's settings?  I will also check on our SSL config issue.

**Comment by laurencei** [comment]
@CaptainHypertext - how did you go with this?

**Comment by CaptainHypertext** [comment]
@laurencei I think clearing the config cache did it, thanks.
