### ISSUE TITLE
Update to laravel 5.6

### ISSUE THREAD

**Issue by marislazda** [eyewitness/eye#40]
Updated laravel to 5.6 and noticed error in logs (Not 100% that it's because of  the framework update but haven't seen it before that)

`[2018-05-20 13:47:35] laravel.ERROR: Call to a member function diffForHumans() on null {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to a member function diffForHumans() on null at /www/vendor/eyewitness/eye/app/Notifications/Messages/Scheduler/Missed.php:38)
[stacktrace]
#0 /www/vendor/eyewitness/eye/app/Notifications/Drivers/Database.php(27): Eyewitness\\Eye\\Notifications\\Messages\\Scheduler\\Missed->meta()
#1 /www/vendor/eyewitness/eye/app/Notifications/Notifier.php(21): Eyewitness\\Eye\\Notifications\\Drivers\\Database->fire(Object(Eyewitness\\Eye\\Repo\\Notifications\\Recipient), Object(Eyewitness\\Eye\\Notifications\\Messages\\Scheduler\\Missed))
#2 /www/vendor/eyewitness/eye/app/Monitors/Scheduler.php(97): Eyewitness\\Eye\\Notifications\\Notifier->alert(Object(Eyewitness\\Eye\\Notifications\\Messages\\Scheduler\\Missed))
#3 /www/vendor/eyewitness/eye/app/Monitors/Scheduler.php(28): Eyewitness\\Eye\\Monitors\\Scheduler->notifyIfChanges(Object(Eyewitness\\Eye\\Repo\\Scheduler))
#4 /www/vendor/eyewitness/eye/app/Commands/PollCommand.php(60): Eyewitness\\Eye\\Monitors\\Scheduler->poll()
#5 [internal function]: Eyewitness\\Eye\\Commands\\PollCommand->handle()
#6 /www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#7 /www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#8 /www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#9 /www/vendor/laravel/framework/src/Illuminate/Container/Container.php(564): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#10 /www/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\\Container\\Container->call(Array)
#11 /www/vendor/symfony/console/Command/Command.php(252): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#12 /www/vendor/laravel/framework/src/Illuminate/Console/Command.php(170): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#13 /www/vendor/symfony/console/Application.php(865): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#14 /www/vendor/symfony/console/Application.php(241): Symfony\\Component\\Console\\Application->doRunCommand(Object(Eyewitness\\Eye\\Commands\\PollCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#15 /www/vendor/symfony/console/Application.php(143): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#16 /www/vendor/laravel/framework/src/Illuminate/Console/Application.php(89): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#17 /www/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(122): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#18 /www/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#19 {main}
`

**Comment by laurencei** [comment]
@marislazda - out of curiosity - did this resolve it?

**Comment by marislazda** [comment]
@laurencei Yes. Don't remember what coused that. 
If I  remember it right - I just updated eye package
