### ISSUE TITLE
Charts values miscalculated with null values

### ISSUE THREAD

**Issue by curunoir** [eyewitness/eye#43]
Hello,

when I was writing a custom witness I was surprised to the values showed in the chart. For example the witness always setted the monitored value to **93**

`$this->setValue(93);`

 and the chart showed various values such **10.02**, **23.43** etc
I finally discovered this was due to my tests when I didn't set any monitored value. It looks like null values in eyewitness_io_history_monitors table were also included in the computed displayed value.
Maybe this can occur in production whith unexpected exceptions, a quick workaround could be to use whereNotNull() on ChartTransformer generateCustom() function

`$history = CustomHistory::where('meta', $witness->getSafeName())->whereNotNull('value')->get()->groupBy(function($item) {`

but maybe there's a better place to take care of it.

**Comment by laurencei** [comment]
Can I ask - in what situation would you sometimes set a value, and not set a value in other cases?

i.e. why not always set the value?

**Comment by curunoir** [comment]
Well that happened writing a custom witness. At first I didn't set the values then I did every time so I guess it is not a real use case. But what happens when an uncaught exception is catched by Eyewitness ? The documentation says it will handle it like a fail but what about the exception is raised and no value setted ?

**Comment by laurencei** [comment]
Yep - good point.

I'll make a change for this.

**Comment by laurencei** [comment]
@curunoir - ok - the latest patch today should handle `null` values correctly and not use them as part of the average charting. Let me know how it goes :)

**Comment by curunoir** [comment]
It looks good, thanks !
