### ISSUE TITLE
 Undefined index: alternate_url in SSL Monitor

### ISSUE THREAD

**Issue by alin-o** [eyewitness/eye#47]
I found this in my error log:
```
Undefined index: alternate_url {"exception":"[object] (ErrorException(code: 0): Undefined index: alternate_url at /var/www/beta.uplogiq.com/releases/105/vendor/eyewitness/eye/app/Monitors/Ssl.php:157)
```

Still, the SSL monitor reports that my SSL Certificate is valid.

**Comment by Dries-Vandenneucker** [comment]
https://www.htbridge.com/ssl/#api

Seems that "alternate_url" is no longer part of the response. At least I don't see it in the "Example of Server Response"

**Comment by laurencei** [comment]
Thanks - should be fixed now in latest patch.
