### ISSUE TITLE
onOneServer schedules cause exception

### ISSUE THREAD

**Issue by hubertnnn** [eyewitness/eye#50]
Call to undefined method Illuminate\Console\Scheduling\Schedule::allowServerToRun()
at /vendor/eyewitness/eye/app/Commands/Framework/ScheduleRunCommand.php:27

This method was renamed in this commit:
https://github.com/laravel/framework/commit/6563ba65b65106198095f1d61f91e0ec542e98dd#diff-0de50829a544cd21193aef291b5a9baf

**Comment by glamorous** [comment]
PR for this issue. This fix is needed because all crons that should run on 1 server only, will fail with a fatal error.
