### ISSUE TITLE
login_disabled not working

### ISSUE THREAD

**Issue by hubertnnn** [eyewitness/eye#51]
When I set 'login_disabled' to true and use a custom middleware for authentication I am redirected to /

**Comment by laurencei** [comment]
Hi @hubertnnn -

Are you able to provide the middleware that is not working? I'm happy to look into it for you

**Comment by hubertnnn** [comment]
It was just a simple gate middleware, nothing related to to eyewitness.

It looked something like this:
```
    public function handle($request, Closure $next)
    {
        if (Gate::denies('administration') {
            abort(404);
        }

        return $next($request);
    }
```

The main issue is in here:
https://github.com/eyewitness/eye/blob/af5f44e51cfe130baba1452ee1e656af29f690b8/app/Http/Controllers/AuthController.php#L18-L20

That probably should be a redirect to dashboard instead of /

**Comment by hubertnnn** [comment]
Also seems like your gate is missing:
```
        if (config('eyewitness.login_disabled', false)) { 
             return $next($request);
        } 
```

**Comment by laurencei** [comment]
Thanks @hubertnnn - I've found the issue and put it a fix (along with a test case to prevent regression).

If you update to the latest beta version and try again - it should be resolved. Please let me know if you have any further issues.
