### ISSUE TITLE
Cannot use with SQL Server

### ISSUE THREAD

**Issue by doubleoh13** [eyewitness/eye#6]
The SQL functions called in the Eyewitness\Eye\Tools\ChartTransformer class cause exceptions due to utilizing database specific functions, specifically date and the group by condition.

```php
$history = Scheduler::select([DB::Raw('avg(time_to_run) as avg_time_to_run'), DB::Raw('DATE(created_at) day')])
                            ->where('scheduler_id', $scheduler->id)
                            ->groupBy('day') 
                            ->get();
```

T-SQL doesn't have a DATE() function and won't group based on the aliased column name.
The migrations are also causing a problem with SQL Server. Server reports that type nvarchar is invalid for AVG() function.

**Comment by laurencei** [comment]
Ok - thanks @doubleoh13.

To be honest I've not used SQL server, so that's why it was missed.

 I'll look into it today and we will definetely support it ASAP.

**Comment by laurencei** [comment]
@doubleoh13 - I've just pushed an update that now uses Laravel collections to do all the logic, so there is no longer a reliance on the database.

Do you mind grabbing the latest version of the beta and trying again? I think this should solve the issue for you.

**Comment by doubleoh13** [comment]
@laurencei - that did work.
