### ISSUE TITLE
Route cache display [minor]

### ISSUE THREAD

**Issue by arukompas** [eyewitness/eye#61]
Hey, just installed EyeWitness (amazing tool!). We don't cache the routes, yet it still says "cached". 

<img width="326" alt="screenshot 2018-10-03 at 09 48 47" src="https://user-images.githubusercontent.com/8697942/46400200-c0458680-c6f1-11e8-986e-e3b47c70169e.png">

**Comment by laurencei** [comment]
Thanks - just fixed it now.
