### ISSUE TITLE
Error running eyewitness:install

### ISSUE THREAD

**Issue by mikemand** [eyewitness/eye#7]
While trying to "run initial checks", I received the following error:

```
SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'meta' cannot be null (SQL: insert into `eyewitness_io_history_monitors` (`type`, `meta`, `record`) values (dns, , [{"class":"IN","host":"","target":"e.root-servers.net","type":
  "NS"},{"class":"IN","host":"","target":"h.root-servers.net","type":"NS"},{"class":"IN","host":"","target":"c.root-servers.net","type":"NS"},{"class":"IN","host":"","target":"j.root-servers.net","type":"NS"},{"class":"IN","host":"","target
  ":"b.root-servers.net","type":"NS"},{"class":"IN","host":"","target":"k.root-servers.net","type":"NS"},{"class":"IN","host":"","target":"i.root-servers.net","type":"NS"},{"class":"IN","host":"","target":"d.root-servers.net","type":"NS"},{
  "class":"IN","host":"","target":"g.root-servers.net","type":"NS"},{"class":"IN","host":"","target":"m.root-servers.net","type":"NS"},{"class":"IN","host":"","target":"l.root-servers.net","type":"NS"},{"class":"IN","host":"","target":"a.ro
  ot-servers.net","type":"NS"},{"class":"IN","host":"","target":"f.root-servers.net","type":"NS"},{"class":"IN","expire":604800,"host":"","minimum-ttl":86400,"mname":"a.root-servers.net","refresh":1800,"retry":900,"rname":"nstld.verisign-gr
  s.com","serial":2018020701,"type":"SOA"}]))
```

My environment:
* Laravel 5.4
* PHP 7.2
* MySQL 5.7.21

**Comment by laurencei** [comment]
Thanks @mikemand,

I've just pushed an update. Can you pull down the latest version and try again? (You will need to refresh the database to re-run the migrations).

Also - can I clarify - did you modify the config file at all before the installation? Or was this a brand new install?

**Comment by mikemand** [comment]
Hi @laurencei,

Thank you for the quick reply!

I did modify the config file; I ran `composer require` on my local machine, added `env('APP_DOMAIN')` so the environments domain will be in the list of domains (see below) and pushed everything up with git so Forge will deploy.

```php
    'application_domains' => [
        env('APP_DOMAIN'),
    ],
```

**Comment by laurencei** [comment]
it looks like `env('APP_DOMAIN')` is returning `""` though? i.e. the value is blank from what I can see in your error log above. 

Can you check and let me know?

**Comment by mikemand** [comment]
Aha! You are correct. That would be my fault. I thought `APP_DOMAIN` was a valid env key. I've set it and after forcing a poll it seems to have worked.

**Comment by laurencei** [comment]
Ok cool. 

In saying that - I'll add a check to detect empty/bad values, so people dont have this problem in the future.

Thanks!!
